name: Greetings

on: [pull_request, issues,push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for figuring out'
        pr-message: 'Thanks for Contribution,are PR team is working on it !!'
